version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3talkdemo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zohzyc9tc3o2"
s3_prefix = "s3talkdemo"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
