AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3lambdatalk

  Sample SAM Template for s3lambdatalk

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MachinifyTalkDemoBucket:
    Type: AWS::S3::Bucket

  SortJSON:
    Type: AWS::Serverless::Function
    Properties:
      Handler: json_sorter.lambda_handler
      Runtime: python3.9
      Timeout: 60
      CodeUri: s3/
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Sid: AllowObjectLambdaAccess
          Effect: Allow
          Action:
          - s3-object-lambda:WriteGetObjectResponse
          Resource: "*"
  HandleUpload:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sort_upload.lambda_handler
      Runtime: python3.9
      Timeout: 60
      CodeUri: s3/
      Policies: AWSLambdaExecute
      Events:
        NewUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref MachinifyTalkDemoBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix      # or "suffix"
                    Value: newupload      # The value to search for in the S3 object key names

